<?php

/************************** Custom Template *****************************/

return array(
	'name'              => esc_attr__( 'About 6', 'boldman' ),    // Template Title
	'template_category' => esc_attr__( 'About', 'boldman' ),	 // Template Category
	'content'           => '<<<TMCONTENTTILLTHIS
[vc_row tm_bgimagefixed="" break_in_responsive="991" full_width="stretch_row" css=".vc_custom_1569474344707{padding-top: 100px !important;padding-bottom: 65px !important;}" tm_responsive_css="20949926|colbreak_no|||||||||colbreak_no|||||10px||40px||colbreak_no||||||||||colbreak_no|||||||||"][vc_column width="1/2"][vc_single_image image="3841" img_size="full"][/vc_column][vc_column width="1/2"][tm-heading h2="With decades of experience
and true commitment to
Handyman Solutions" h4="Who We Are" reverse_heading="true"][/tm-heading][vc_column_text css=".vc_custom_1569403585462{margin-top: -13px !important;margin-bottom: 7px !important;}"]We work to ensure people’s comfort at their home, and to provide the best and the fastest help at fair prices. We stand for quality, safety and credibility, so you could be sure about our work. Initially we started as a company specializing in household maintenance.Magna aliqua. Uex ea commodo consequat. Dt enim ad minim veniam, quis nostrud exercitation ullam laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor enderit in voluptate velit esse cillum.[/vc_column_text][vc_row_inner][vc_column_inner width="1/2" css=".vc_custom_1569403685322{padding-right: 0px !important;}"][tm-list tm_textcolor="black" icon_icon_fontawesome="fa fa-check" line1="JTIwUm91dGluZSUyMGFuZCUyMG1lZGljYWwlMjBjYXJl" line2="RXhjZWxsZW5jZSUyMGluJTIwSGVhbHRoY2FyZSUyMGV2ZXJ5" line3="JTIwQnVpbGRpbmclMjBhJTIwaGVhbHRoeSUyMGVudmlyb25tZW50Lg=="][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1569495722754{padding-right: 0px !important;}" tm_responsive_css="25425251|colbreak_no|||||||||colbreak_no|-32px||||||||colbreak_no||||||||||colbreak_no|||||||||"][tm-list tm_textcolor="black" icon_icon_fontawesome="fa fa-check" line1="JTIwUm91dGluZSUyMGFuZCUyMG1lZGljYWwlMjBjYXJl" line2="RXhjZWxsZW5jZSUyMGluJTIwSGVhbHRoY2FyZSUyMGV2ZXJ5" line3="JTIwQnVpbGRpbmclMjBhJTIwaGVhbHRoeSUyMGVudmlyb25tZW50Lg=="][/vc_column_inner][/vc_row_inner][vc_separator color="custom" accent_color="#efecec" css=".vc_custom_1569406145911{margin-top: 7px !important;margin-bottom: 0px !important;}"][vc_row_inner el_class="ttm-col-seprator tm-column-inline"][vc_column_inner width="5/12" css=".vc_custom_1569496782547{padding-top: 30px !important;padding-right: 30px !important;}"][tm-servicebox h2="25 Years" reverse_heading="" i_type="fontawesome" i_icon_fontawesome="fa fa-briefcase" i_color="white" i_background_style="rounded" i_background_color="skincolor" i_size="sm" el_class="tm-0px-heading-margin" css=".vc_custom_1569481104871{margin-bottom: 7px !important;}"]Of Field Experiance[/tm-servicebox][/vc_column_inner][vc_column_inner width="7/12" css=".vc_custom_1569405935590{padding-top: 21px !important;padding-left: 40px !important;}"][vc_single_image image="3842" img_size="full"][tm-custom-heading text="Jhon Martin" font_container="tag:h2|font_size:20px|text_align:center|line_height:26px" css=".vc_custom_1569411400797{margin-top: -105px !important;margin-bottom: 0px !important;padding-left: 85px !important;}"][tm-custom-heading text="Chairman &amp; founder" font_container="tag:p|text_align:center" css=".vc_custom_1569480779055{padding-left: 125px !important;}"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
TMCONTENTTILLTHIS',
);
