<?php

/************************** Custom Template *****************************/

return array(
	'name'              => esc_attr__( 'About 3', 'boldman' ),    // Template Title
	'template_category' => esc_attr__( 'About', 'boldman' ),	 // Template Category
	'content'           => '<<<TMCONTENTTILLTHIS
[vc_row tm_bgimagefixed="" break_in_responsive="991" full_width="stretch_row" css=".vc_custom_1550053104872{padding-bottom: 0px !important;}" tm_responsive_css="29815009|colbreak_no|||||||||colbreak_no|||||15px||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column width="1/2" css=".vc_custom_1548743778981{padding-top: 40px !important;}"][tm-heading h2="Introduce About Boldman" h4="who we are" reverse_heading="true"][/tm-heading][vc_column_text]We work to ensure people’s comfort at their home, and to provide the best and the fastest help at fair prices. We stand for quality, safety and credibility, so you could be sure about our work. Initially we started as a company specializing in household maintenance.[/vc_column_text][vc_row_inner][vc_column_inner el_class="servicebox-number tm-sbox-border-style"][tm-servicebox add_icon="before-heading" h2="Reliable, and Professional Handyman Great Services" h2_font_container="font_size:18px|line_height:24px" reverse_heading="" i_type="themify" i_icon_themify="themifyicon ti-info" i_color="black" i_background_style="rounded" i_size="sm" use_custom_fonts_h2="true" el_class="tm-0px-heading-margin"][/tm-servicebox][tm-servicebox add_icon="before-heading" h2="Repairing or Replacing Broken Garbage Disposals" h2_font_container="font_size:18px|line_height:24px" i_type="themify" i_icon_themify="themifyicon ti-info" i_color="black" i_background_style="rounded" i_size="sm" use_custom_fonts_h2="true" el_class="tm-0px-heading-margin"][/tm-servicebox][tm-servicebox add_icon="before-heading" h2="Install Outlets, Switches, and other Electrical Components" h2_font_container="font_size:18px|line_height:24px" i_type="themify" i_icon_themify="themifyicon ti-info" i_color="black" i_background_style="rounded" i_size="sm" use_custom_fonts_h2="true" el_class="tm-0px-heading-margin"][/tm-servicebox][/vc_column_inner][/vc_row_inner][/vc_column][vc_column width="1/2" el_class="tm-reset-content-center-991" tm_responsive_css="95463998|colbreak_no|||||||||colbreak_no|||||10px||||colbreak_no||||||||||colbreak_no|||||||||"][vc_single_image image="3645" img_size="full" alignment="right"][/vc_column][/vc_row]
TMCONTENTTILLTHIS',
);
