<?php

/************************** Custom Template *****************************/

return array(
	'name'              => esc_attr__( 'FAQ 1', 'boldman' ),    // Template Title
	'template_category' => esc_attr__( 'FAQ', 'boldman' ),	 // Template Category
	'content'           => '<<<TMCONTENTTILLTHIS
[vc_row tm_bgimagefixed="" full_width="stretch_row" css=".vc_custom_1550138683203{padding-bottom: 15px !important;}" tm_responsive_css="41477175|colbreak_no|||||||||colbreak_no|||||60px||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column][tm-heading h2="Do you have Questions?" txt_align="center" reverse_heading=""]Lorem Ipsum is simply dummy text of the printing and typesetting industry has been the industry’s standard dummy when an unknown printer.[/tm-heading][/vc_column][/vc_row][vc_row tm_bgimagefixed="" full_width="stretch_row" css=".vc_custom_1550138834634{padding-top: 0px !important;padding-bottom: 60px !important;}" tm_responsive_css="10979502|colbreak_no|||||||||colbreak_no|||||||40px||colbreak_no|||||||20px|||colbreak_no|||||||||"][vc_column width="1/2"][vc_single_image image="3627" img_size="full" style="vc_box_rounded"][vc_row_inner][vc_column_inner css=".vc_custom_1549016098192{margin-top: -270px !important;}"][tm-icon type="themify" icon_themify="themifyicon ti-control-play" color="white" background_style="rounded" background_color="skincolor" align="center" link="url:%23|||" el_class="tm_prettyphoto"][/vc_column_inner][/vc_row_inner][/vc_column][vc_column width="1/2"][vc_tta_accordion style="outline" color="grey" gap="15" c_position="right" active_section="1"][vc_tta_section title="We bring together best people to around the world" tab_id="1549004535827-b3afa67a-3a5e"][vc_column_text]Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.[/vc_column_text][/vc_tta_section][vc_tta_section title="Kitchen Cabinets Remodeling &amp; Renovation" tab_id="1549005508759-77cb3376-8b04"][vc_column_text]Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.[/vc_column_text][/vc_tta_section][vc_tta_section title="Boldman have a unique way of the working?" tab_id="1549005507765-5cdb0b8d-161b"][vc_column_text]Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.[/vc_column_text][/vc_tta_section][vc_tta_section title="Hire an experienced Plumber" tab_id="1549005502002-bb6438ce-15a8"][vc_column_text]Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.[/vc_column_text][/vc_tta_section][vc_tta_section title="Simple Steps for Home Renovation" tab_id="1549005500042-c476fcc6-1db8"][vc_column_text]Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.[/vc_column_text][/vc_tta_section][/vc_tta_accordion][/vc_column][/vc_row]	
TMCONTENTTILLTHIS',
);
