<?php

/************************** Custom Template *****************************/

return array(
	'name'              => esc_attr__( 'Portfolio Style2', 'boldman' ),    // Template Title
	'template_category' => esc_attr__( 'Portfolio', 'boldman' ),	 // Template Category
	// 'new'            => true,                                 // Enable to display New badge.
	'content'           => '<<<TMCONTENTTILLTHIS
[vc_row tm_bgcolor="darkgrey" tm_bgimagefixed="" break_in_responsive="991" full_width="stretch_row" css=".vc_custom_1550245452124{padding-top: 0px !important;padding-bottom: 0px !important;background-image: url(http://boldman.themetechmount.com/boldman-data/wp-content/uploads/sites/6/2019/02/post-one.jpg?id=3626) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" tm_responsive_css="77151585|colbreak_no|||||||||colbreak_no|||||||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column][vc_row_inner][vc_column_inner width="1/4"][/vc_column_inner][vc_column_inner tm_bgcolor="skincolor" width="1/2" css=".vc_custom_1550053883925{margin-top: -130px !important;padding-top: 40px !important;padding-right: 0px !important;padding-bottom: 5px !important;padding-left: 0px !important;}" tm_responsive_css="91828575|colbreak_no|||||||||colbreak_no|||||||||colbreak_no||||||||||colbreak_no|||||||||"][tm-icon type="kw_boldman" icon_kw_boldman="kw_boldman flaticon-handyman-tools" color="white" background_style="rounded" background_color="black" size="sm" align="center" css=".vc_custom_1548927779466{margin-bottom: 20px !important;}"][tm-heading h2="Our Latest Projects" h4="Recently Completed" txt_align="center" reverse_heading="true" seperator="none"][/tm-heading][/vc_column_inner][vc_column_inner width="1/4"][/vc_column_inner][/vc_row_inner][vc_row_inner css=".vc_custom_1550896117028{margin-right: 0px !important;margin-left: 0px !important;}" tm_responsive_css="94005144|colbreak_no|||||||||colbreak_no|-1px|-15px|-1px|-15px|||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column_inner tm_bgcolor="white" css=".vc_custom_1548132126979{padding-top: 20px !important;padding-right: 20px !important;padding-bottom: 15px !important;padding-left: 20px !important;}"][tm-portfoliobox h2="" show="6" box_spacing="5px"][/tm-portfoliobox][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner width="1/4"][/vc_column_inner][vc_column_inner tm_bgcolor="skincolor" width="1/2" css=".vc_custom_1550904178297{padding-top: 55px !important;padding-right: 0px !important;padding-bottom: 80px !important;padding-left: 0px !important;}" tm_responsive_css="22805168|colbreak_no|||||||||colbreak_no|||-1px||50px||28px||colbreak_no||||||||||colbreak_no|||||||||"][tm-btn title="VIEW MORE GALLERY" style="outline" shape="square" color="white" align="center" link="url:%23|||"][/vc_column_inner][vc_column_inner width="1/4"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
TMCONTENTTILLTHIS',
);
