<?php

/************************** Custom Template *****************************/

return array(
	'name'              => esc_attr__( 'Services Style 1', 'boldman' ),    // Template Title
	'template_category' => esc_attr__( 'Services', 'boldman' ),	 // Template Category
	// 'new'            => true,                                 // Enable to display New badge.
	'content'           => '<<<TMCONTENTTILLTHIS
[vc_row tm_bgimagefixed="" css=".vc_custom_1560578912579{padding-top: 78px !important;padding-bottom: 84px !important;}" tm_responsive_css="77233766|colbreak_no|||||||||colbreak_no|||||50px||35px||colbreak_no||||||||||colbreak_no|||||||||"][vc_column][tm-heading h2="What You Will Get Form
Us Check It" h4="our services" txt_align="center" reverse_heading="true"]Raising a heavy fur muff that covered the whole of her lower arm towards the viewer regor then turned to look out the window[/tm-heading][vc_row_inner equal_height="yes" el_class="tm-sbox-bordered-style" css=".vc_custom_1560514506402{margin-right: 0px !important;margin-left: 0px !important;padding-bottom: 49px !important;}"][vc_column_inner width="1/4"][tm-servicebox add_icon="top-left" h2="Home Maintenance" reverse_heading="" add_button="bottom" btn_color="black" btn_add_icon="" i_type="kw_boldman" i_icon_kw_boldman="kw_boldman flaticon-house" i_size="xl" btn_link="url:%23|||"]Sed ut perspiciatis unde omnis iste natus error sit voluptatem accustium lo.[/tm-servicebox][/vc_column_inner][vc_column_inner width="1/4"][tm-servicebox add_icon="top-left" h2="Home Painting" reverse_heading="" add_button="bottom" btn_color="black" btn_add_icon="" i_type="kw_boldman" i_icon_kw_boldman="kw_boldman flaticon-paint-roller-1" i_size="xl" btn_link="url:%23|||"]Sed ut perspiciatis unde omnis iste natus error sit voluptatem accustium lo.[/tm-servicebox][/vc_column_inner][vc_column_inner width="1/4"][tm-servicebox add_icon="top-left" h2="Home installation" reverse_heading="" add_button="bottom" btn_color="black" btn_add_icon="" i_type="kw_boldman" i_icon_kw_boldman="kw_boldman flaticon-welder" i_size="xl" btn_link="url:%23|||"]Sed ut perspiciatis unde omnis iste natus error sit voluptatem accustium lo.[/tm-servicebox][/vc_column_inner][vc_column_inner width="1/4"][tm-servicebox add_icon="top-left" h2="Home Renovation" reverse_heading="" add_button="bottom" btn_color="black" btn_add_icon="" i_type="kw_boldman" i_icon_kw_boldman="kw_boldman flaticon-carpenter" i_size="xl" btn_link="url:%23|||"]Sed ut perspiciatis unde omnis iste natus error sit voluptatem accustium lo.[/tm-servicebox][/vc_column_inner][/vc_row_inner][vc_raw_html css=".vc_custom_1560514889376{margin-bottom: 0px !important;}"]JTNDcCUyMGNsYXNzJTNEJTIydG0tY2VudGVyLXRleHQlMjIlM0VEb24lRTIlODAlOTl0JTIwaGVzaXRhdGUlMkMlMjBjb250YWN0JTIwdXMlMjBmb3IlMjBiZXR0ZXIlMjBoZWxwJTIwYW5kJTIwc2VydmljZXMuJTIwJTNDdSUzRSUzQ2ElMjBocmVmJTNEJTIyJTIzJTIyJTNFRXhwbG9yZSUyME1vcmUlMjBUZWFtJTNDJTJGYSUzRSUzQyUyRnUlM0UlM0MlMkZwJTNF[/vc_raw_html][/vc_column][/vc_row]
TMCONTENTTILLTHIS',
);
