<?php

/************************** Custom Template *****************************/

return array(
	'name'              => esc_attr__( 'Testimonial Style 1', 'boldman' ),    // Template Title
	'template_category' => esc_attr__( 'Testimonial', 'boldman' ),	 // Template Category
	// 'new'            => true,                                 // Enable to display New badge.
	'content'           => '<<<TMCONTENTTILLTHIS
[vc_row tm_bgcolor="darkgrey" tm_bgimagefixed="" break_in_responsive="991" tm_zindex="1" full_width="stretch_row" css=".vc_custom_1549971956885{margin-top: -1px !important;padding-top: 0px !important;padding-bottom: 0px !important;}"][vc_column reduce_extra_padding="991" width="5/12" css=".vc_custom_1549975517882{margin-bottom: -60px !important;}" tm_responsive_css="16278315|colbreak_no|||||||||colbreak_no|||0px||55px||||colbreak_no||||||||||colbreak_no|||||||||"][vc_single_image image="3633" img_size="full" alignment="center" css=".vc_custom_1550244739987{margin-bottom: 0px !important;}"][/vc_column][vc_column width="7/12" css=".vc_custom_1549975543719{padding-top: 82px !important;padding-right: 0px !important;padding-left: 40px !important;}" tm_responsive_css="84747839|colbreak_no|||||||||colbreak_no|||||40px|||15px|colbreak_no||||||||||colbreak_no|||||||||"][tm-testimonialbox h2="" reverse_heading="" carousel_nav="hide"][/tm-testimonialbox][vc_row_inner css=".vc_custom_1550049776238{margin-right: 0px !important;margin-left: 0px !important;}" tm_responsive_css="28271194|colbreak_no|||||||||colbreak_no|||||||||colbreak_no||||-10px|||20px|||colbreak_no|||||||||"][vc_column_inner width="1/3" css=".vc_custom_1547806118268{padding-right: 0px !important;padding-left: 0px !important;}"][tm-facts-in-digits title="Projects Completed" view="lefticon" add_border="" i_type="themify" i_icon_themify="themifyicon ti-briefcase" digit="350" aftertextstyle="span" interval="20" after="+"][/vc_column_inner][vc_column_inner width="1/3" css=".vc_custom_1547806210774{padding-right: 0px !important;padding-left: 0px !important;}"][tm-facts-in-digits title="Work Employed" view="lefticon" add_border="" i_type="themify" i_icon_themify="themifyicon ti-user" digit="120" aftertextstyle="span" interval="20" after="+"][/vc_column_inner][vc_column_inner width="1/3" css=".vc_custom_1547806215045{padding-right: 0px !important;padding-left: 0px !important;}"][tm-facts-in-digits title="Years Experiance" view="lefticon" add_border="" i_type="themify" i_icon_themify="themifyicon ti-cup" digit="30" aftertextstyle="span" after="+"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
TMCONTENTTILLTHIS',
);
